service: my-app-shared-infra

provider:
  name: aws
  region: ${env:AWS_REGION}
  stage: shared
  tags: ${file(../../config/default-tags.yml)}

resources:
  Resources:
    DeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub 'my-app-deployments-bucket-${AWS::Region}'
    DeploymentBucketParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /my-app/shared/buckets/deployments
        Value: !Ref DeploymentBucket
        Type: String
