Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'my-app-deployments-bucket-${AWS::Region}'
  DeploymentBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /my-app/shared/buckets/deployments
      Value: !Ref DeploymentBucket
      Type: String
